### ISSUE TITLE
WebUSB + libusb + pthreads

### ISSUE THREAD

**Issue by goncalomb** [goncalomb/sane-wasm#1]
Before the public release of sane-wasm I spent A LOT of time patching and debugging @RReverser's initial WebUSB backend for libusb (libusb/libusb#1057) to add basic multi-threaded support. This was basically my introduction to Emscripten and its inner workings.

Multi-threaded support at the libusb level is required for sane-wasm because normally the SANE backends open the USB device on the main thread, but then they spawn a new thread to do the actual scanning. Changing this behavior on all backends is unfeasible.

https://github.com/goncalomb/sane-wasm/blob/3100bc98c037cd8ff63ea19c8dd98e3f13931b2f/deps/libusb.patch

The patch adds very rudimentary support for phreads by proxying critical calls back to the main thread, where the device was originally opened. This is required because we cannot share WebUSB USBDevice handles (or emscripten::val) across to the Service Workers (Emscripten threads).

**This approach works for now. But I'm opening this issue to continue the discussion on this topic.** This is by no means fixed or a complete solution.

Some current shortcomings are:

- not all calls are being proxied to the main thread (fixable, and required for complete support)
- the event system is also far from ideal, we are just posting messages to all threads
- deadlock issues with the main thread waiting for a worker thread (pthread_join), while the worker thread is waiting for a USB transaction on the main thread, "fixed", but not pretty
- overall very unappealing implementation
- not thoroughly tested (I only used the SANE pixma backend for testing)

It remains to be seen if this is the correct approach or the implementation should just be rewritten from scratch, maybe using a dedicated thread for all the WebUSB calls? The original pull request (libusb/libusb#1057) also has some discussion on this topic.

Contributions are welcome.

**Comment by RReverser** [comment]
I would love for WebUSB to support multithreading natively as @reillyeon suggested it might be someday on the original thread (hehe, no pun intended), but meanwhile using Emscripten's proxying API sounds like a promising solution to fill that gap.

I think main thread instead of a dedicated thread is fine since WebUSB is already asynchronous and is not supposed to block the main thread for long anyway.

I don't have capacity to review the code right now but when you polish it up, I think it's worth creating a PR upstream on the libusb repo. When you do, please tag me and I'll try to take a look.

**Comment by RReverser** [comment]
My only note from a quick glance is that I'd probably try to extract some helper to avoid repeated duplication if thread ID checks & proxying or calling locally.

Also most (all?) libusb functions accept only one argument anyway so it might be cheaper to just pass the original function & argument directly as callback & argument to ` emscripten_proxy_sync` instead of using another indirection in the task wrapper.

**Comment by goncalomb** [comment]
Multithreading support is now available upstream (libusb/libusb#1339), I can abandon my attempt and close this issue.

Thanks @RReverser once again.
